---
baseURL: https://mostafabita.netlify.app/
title: I'm Mostafa
author: Mostafa Bita
copyright: © Copyright 2020 Mostafa Bita
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
theme: hugo-PaperMod
params:
  owner: Mostafa Bita
  description: Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod
  author: Theme PaperMod
  ShowReadingTime: true
  contentTypeName: posts
  defaultTheme: auto
  ShowShareButtons: true
  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: It's Mostafa Bita
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/mostafabita"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/4497920/mostafa-bita"
    - name: github
      url: "https://github.com/mostafabita"
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
menu:
  main:
    - url: "/series/"
      name: Portfolio
      weight: 3
    - url: "/tags/"
      name: Resume
      weight: 2
    - url: "/archives/"
      name: Posts
      weight: 1
taxonomies:
  category: categories
  tag: tags
  series: series
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
